-- VALORAE Supabase Sync v3
-- Execute no SQL Editor do Supabase.
-- Modelo: login/senha pelo Supabase Auth + Proxy VALORAE com service_role no Vercel.

create table if not exists public.valorae_sync_clients (
  user_id text primary key,
  device_id text,
  client_secret_hash text not null,
  app_version text,
  source text default 'apk-android',
  schema_version integer default 2,
  revoked boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  last_seen_at timestamptz default now()
);

create table if not exists public.valorae_user_snapshots (
  id bigint generated by default as identity primary key,
  user_id text not null,
  domain text not null,
  snapshot_key text not null,
  schema_version integer default 3,
  app_version text,
  device_id text,
  source text,
  encrypted boolean default false,
  payload jsonb,
  payload_ciphertext text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint valorae_user_snapshots_unique unique (user_id, domain, snapshot_key),
  constraint valorae_user_snapshots_payload_check check (
    (encrypted = false and payload is not null) or
    (encrypted = true and payload_ciphertext is not null)
  )
);

create table if not exists public.valorae_transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  client_tx_id text not null,
  ticker text not null,
  name text,
  quantity numeric default 0,
  purchase_price numeric default 0,
  transaction_date bigint,
  asset_type text,
  is_sell boolean default false,
  broker text,
  sector text,
  notes text,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint valorae_transactions_unique unique (user_id, client_tx_id)
);

create table if not exists public.valorae_dividend_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_key text not null,
  ticker text not null,
  date_com text,
  payment_date text,
  value_per_share numeric default 0,
  quantity numeric default 0,
  estimated_amount numeric default 0,
  status text,
  category text default 'future',
  source text,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint valorae_dividend_events_unique unique (user_id, event_key)
);

create index if not exists idx_valorae_sync_clients_last_seen on public.valorae_sync_clients (last_seen_at desc);
create index if not exists idx_valorae_sync_clients_revoked on public.valorae_sync_clients (revoked);
create index if not exists idx_valorae_snapshots_user_domain on public.valorae_user_snapshots (user_id, domain);
create index if not exists idx_valorae_snapshots_updated_at on public.valorae_user_snapshots (updated_at desc);
create index if not exists idx_valorae_snapshots_payload_gin on public.valorae_user_snapshots using gin (payload);
create index if not exists idx_valorae_transactions_user_ticker on public.valorae_transactions (user_id, ticker);
create index if not exists idx_valorae_transactions_user_date on public.valorae_transactions (user_id, transaction_date desc);
create index if not exists idx_valorae_dividends_user_ticker on public.valorae_dividend_events (user_id, ticker);
create index if not exists idx_valorae_dividends_user_category on public.valorae_dividend_events (user_id, category);
create index if not exists idx_valorae_dividends_user_payment on public.valorae_dividend_events (user_id, payment_date);

alter table public.valorae_sync_clients enable row level security;
alter table public.valorae_user_snapshots enable row level security;
alter table public.valorae_transactions enable row level security;
alter table public.valorae_dividend_events enable row level security;

-- O Proxy usa service_role e ignora RLS no backend.
-- As políticas abaixo permitem acesso direto seguro se o APK usar o JWT do Supabase Auth.
drop policy if exists valorae_snapshots_owner_select on public.valorae_user_snapshots;
create policy valorae_snapshots_owner_select on public.valorae_user_snapshots
for select using (auth.uid()::text = user_id);

drop policy if exists valorae_snapshots_owner_write on public.valorae_user_snapshots;
create policy valorae_snapshots_owner_write on public.valorae_user_snapshots
for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);

drop policy if exists valorae_transactions_owner_select on public.valorae_transactions;
create policy valorae_transactions_owner_select on public.valorae_transactions
for select using (auth.uid()::text = user_id);

drop policy if exists valorae_transactions_owner_write on public.valorae_transactions;
create policy valorae_transactions_owner_write on public.valorae_transactions
for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);

drop policy if exists valorae_dividends_owner_select on public.valorae_dividend_events;
create policy valorae_dividends_owner_select on public.valorae_dividend_events
for select using (auth.uid()::text = user_id);

drop policy if exists valorae_dividends_owner_write on public.valorae_dividend_events;
create policy valorae_dividends_owner_write on public.valorae_dividend_events
for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);

create or replace function public.valorae_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_valorae_sync_clients_updated_at on public.valorae_sync_clients;
create trigger trg_valorae_sync_clients_updated_at
before update on public.valorae_sync_clients
for each row execute function public.valorae_touch_updated_at();

drop trigger if exists trg_valorae_user_snapshots_updated_at on public.valorae_user_snapshots;
create trigger trg_valorae_user_snapshots_updated_at
before update on public.valorae_user_snapshots
for each row execute function public.valorae_touch_updated_at();

drop trigger if exists trg_valorae_transactions_updated_at on public.valorae_transactions;
create trigger trg_valorae_transactions_updated_at
before update on public.valorae_transactions
for each row execute function public.valorae_touch_updated_at();

drop trigger if exists trg_valorae_dividends_updated_at on public.valorae_dividend_events;
create trigger trg_valorae_dividends_updated_at
before update on public.valorae_dividend_events
for each row execute function public.valorae_touch_updated_at();


-- VALORAE Dividendos oficiais globais v4
-- Camada recomendada para separar evento oficial por ticker do cálculo de elegibilidade por usuário.
create table if not exists public.valorae_official_dividend_events (
  id bigint generated by default as identity primary key,
  ticker text not null,
  event_key text not null,
  date_com text,
  payment_date text,
  value_per_share numeric default 0,
  type text,
  status text,
  asset_class text,
  source text,
  raw_payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint valorae_official_dividend_events_unique unique (ticker, event_key)
);

create table if not exists public.valorae_user_dividend_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_key text not null,
  ticker text not null,
  quantity_at_date numeric default 0,
  gross_amount numeric default 0,
  net_amount numeric default 0,
  eligibility_status text,
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint valorae_user_dividend_events_unique unique (user_id, event_key)
);

create index if not exists idx_valorae_official_dividends_ticker on public.valorae_official_dividend_events (ticker);
create index if not exists idx_valorae_official_dividends_payment on public.valorae_official_dividend_events (payment_date);
create index if not exists idx_valorae_user_dividends_user_ticker on public.valorae_user_dividend_events (user_id, ticker);
create index if not exists idx_valorae_user_dividends_event_key on public.valorae_user_dividend_events (event_key);

alter table public.valorae_official_dividend_events enable row level security;
alter table public.valorae_user_dividend_events enable row level security;

drop policy if exists valorae_official_dividends_public_select on public.valorae_official_dividend_events;
create policy valorae_official_dividends_public_select on public.valorae_official_dividend_events
for select using (true);

drop policy if exists valorae_user_dividends_owner_select on public.valorae_user_dividend_events;
create policy valorae_user_dividends_owner_select on public.valorae_user_dividend_events
for select using (auth.uid()::text = user_id);

drop policy if exists valorae_user_dividends_owner_write on public.valorae_user_dividend_events;
create policy valorae_user_dividends_owner_write on public.valorae_user_dividend_events
for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);

drop trigger if exists trg_valorae_official_dividends_updated_at on public.valorae_official_dividend_events;
create trigger trg_valorae_official_dividends_updated_at
before update on public.valorae_official_dividend_events
for each row execute function public.valorae_touch_updated_at();

drop trigger if exists trg_valorae_user_dividends_updated_at on public.valorae_user_dividend_events;
create trigger trg_valorae_user_dividends_updated_at
before update on public.valorae_user_dividend_events
for each row execute function public.valorae_touch_updated_at();
