import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readMinimalFinancialSql } from './helpers/minimal-financial-sql.js';
const route=fs.readFileSync(new URL('../routes/sync.js',import.meta.url),'utf8');
const shared=fs.readFileSync(new URL('../lib/state/shared-state-foundation.js',import.meta.url),'utf8');
const sql = readMinimalFinancialSql();
assert.match(route,/snapshotsEnabled:\s*false/);
assert.match(route,/backupsEnabled:\s*false/);
assert.match(route,/monitorPersistenceEnabled:\s*false/);
assert.match(route,/sharedRuntimeStateEnabled:\s*false/);
assert.match(shared,/return boolValue\(process\.env\.VALORAE_SHARED_STATE_ENABLED, true\) \? 'memory' : 'off'/);
assert.equal(fs.existsSync(new URL('../lib/observability/monitor-persistence.js',import.meta.url)),false);
const beforeMigration=sql.slice(0,sql.indexOf('-- Migração única do legado.'));
assert.doesNotMatch(beforeMigration,/create table.*(?:snapshot|backup|monitor|runtime_shared|sync_clients)/is);
assert.doesNotMatch(beforeMigration,/\bpayload\s+jsonb\b/i);
console.log('Supabase resource optimization minimal v3 OK');
