import assert from 'node:assert/strict';
import fs from 'node:fs';
const route=fs.readFileSync(new URL('../routes/sync.js',import.meta.url),'utf8');
const sql=fs.readFileSync(new URL('../supabase/013_valorae_minimal_financial_sync_v2.sql',import.meta.url),'utf8');
assert.match(route,/auth\/v1\/user/);
assert.match(route,/valorae_financial_download_v2/);
assert.match(route,/valorae_financial_upload_transactions_v2/);
assert.match(route,/valorae_financial_upload_dividends_v2/);
assert.doesNotMatch(route,/VALORAE_SUPABASE_TRANSACTIONS_TABLE|VALORAE_SUPABASE_SNAPSHOTS_TABLE/);
assert.deepEqual([...sql.matchAll(/create table if not exists public\.([a-z0-9_]+)/gi)].map(m=>m[1]),['valorae_financial_transactions','valorae_financial_dividends']);
console.log('Supabase minimal cloud primary v2 OK');
