import assert from 'node:assert/strict';
import { _test } from '../routes/sync.js';
const event=_test.normalizeDividend({event_key:'legacy-div',symbol:'BVMF:BBAS3F',date_com:'2026-01-10',payment_date:'2026-02-10',value_per_share:'0.75',estimated_amount:'7.5',quantity:'10',status:'pago',source:'LEGACY'});
assert.match(event.eventId,/^div-[a-f0-9]{64}$/);
assert.notEqual(event.eventId,'legacy-div');
assert.equal(event.ticker,'BBAS3');
assert.equal(event.dateCom,'2026-01-10');
assert.equal(event.paymentDate,'2026-02-10');
assert.equal(event.valuePerShare,0.75);
assert.equal(event.estimatedAmount,7.5);
console.log('legacy dividend schema normalization minimal v2 OK');
