import assert from 'node:assert/strict';
import { _test } from '../routes/sync.js';
const row={ticker:'PETR4',transaction_date:'2026-01-01',operation:'COMPRA',quantity:1,purchase_price:30,gross_value:30,source:'B3'};
const a=_test.normalizeTransaction(row);
const b=_test.normalizeTransaction({...row});
assert.match(a.clientTxId,/^valorae-[a-f0-9]+$/);
assert.equal(a.clientTxId,b.clientTxId);
assert.equal(a.symbol,'PETR4');
assert.equal(a.grossValue,30);
console.log('legacy client transaction id regression minimal v2 OK');
