import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readMinimalFinancialSql } from './helpers/minimal-financial-sql.js';
const route=fs.readFileSync(new URL('../routes/sync.js',import.meta.url),'utf8');
const sql = readMinimalFinancialSql();
assert.match(route,/DOWNLOAD_RPC = 'valorae_financial_download_v2'/);
assert.doesNotMatch(route,/CURSOR_SECRET|HMAC|encodeCursor|decodeCursor|next_cursor|next_offset/);
assert.match(sql,/jsonb_agg\(jsonb_build_object\([\s\S]*from public\.valorae_financial_transactions/i);
assert.match(sql,/where t\.user_id = p_user_id/);
console.log('transaction restore is deployment-stable without cursor OK');
