
(()=>{
const _origHtml = Object.getOwnPropertyDescriptor(Element.prototype, 'innerHTML');
Object.defineProperty(Element.prototype, 'innerHTML', {
  get: function() { return _origHtml.get.call(this); },
  set: function(val) { if (this.__rawHtml === val) return; this.__rawHtml = val; _origHtml.set.call(this, val); }
});
const $=id=>document.getElementById(id), q=(s,r=document)=>Array.from(r.querySelectorAll(s));
const state={metrics:null,feed:[],filtered:[],selected:null,paused:false,timer:null,lastBench:null,hidden:false,launchPatch:'21.12.31-monitor-experience-redesign'};
const pageAliases={overview:'command',feed:'output',charts:'performance',routes:'performance',pipeline:'performance',vercel:'performance',performance:'performance',quality:'quality',fieldguard:'quality',payloadbudget:'quality',actionplan:'quality',enginematurity:'quality',launch:'quality',maturity:'quality',integration:'integration',manifest:'integration',prompts:'integration',features:'integration',technology:'integration',modules:'integration',benchmark:'diagnostics',diagnostics:'diagnostics',tests:'diagnostics'};
const moduleGroups=[['entrypoints','Entrada HTTP e Vercel','api/router.js, routes/_router.js, lib/http/route.js, lib/observability/server-metrics.js'],['engine-core','Núcleo Valorae Engine','lib/Valorae-engine.js, performance/profile.js, resilience/engine-policy.js'],['fetch-resilience','Busca, resiliência e cache','inflight, circuit-breaker, error-classifier, failure-cache, scrape-result-cache'],['normalization','Normalização e precisão','normalizers/universal.js, normalizers/numbers.js, quality/chart-series.js'],['app-contracts','Contratos para apps','appPayload, appRenderContract, appDataContract, appSyncEnvelope, appMobileSnapshot, appResponseIntegrity'],['monitor-ui','Monitor do proxy','public/server.html, index.html, manifest, service-worker'],['audits-tests','Auditorias e testes','test/*.js, scripts/audit-*.js, build-vercel-safe.js']];
const features=['Profiler de runtime por etapa do Valorae-engine.js','Gate final de lançamento pessoal por payload','Endpoint /api/v1/engine/performance para gargalos','Captura profunda de respostas sendJson, res.end e write+end','Feed de saída com payloadPreview limitado e seguro','Contrato oficial view=app para APK/Web','Snapshot mobile compacto para primeira pintura','ChartSeries normalizado para formatos heterogêneos','Cache em memória com stale-if-error e coalescing','Circuit breaker por fonte pública','Benchmark rápido e profundo no próprio monitor','Contratos especializados para Ações e FIIs','fieldConsistencyGuard, payloadBudget e assetActionPlan'];
const prompts=['Integre meu app Android ao VALORAE usando /api/v1/asset?ticker=PETR4&view=app. Renderize appMobileSnapshot primeiro, depois appPayload, e respeite appSyncEnvelope/cacheSafe.','Audite esta resposta do VALORAE: verifique appResponseIntegrity, fieldConsistencyGuard, payloadBudget e assetActionPlan antes de substituir o cache local.','Crie uma tela Web responsiva para exibir quote, métricas, chartSeries e dividendos usando o contrato view=app do VALORAE Engine.'];
const tech=[['Router único','Todas as rotas /api/* passam por api/router.js e routes/_router.js para caber no Vercel Free.'],['Engine central','lib/Valorae-engine.js permanece como núcleo, com módulos auxiliares ao redor.'],['Observabilidade','/api/server/metrics expõe proxyOutputMonitor, deliveryHarmony, Vercel runtime e readiness.'],['PWA leve','HTML/CSS/JS puro, sem dependências externas, service worker sem cache de /api.']];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(n){return Number.isFinite(+n)?new Intl.NumberFormat('pt-BR').format(+n):'—'}
function fmtMs(n){return Number.isFinite(+n)?`${Math.round(+n)}ms`:'—'}
function fmtBytes(n){n=+n||0;if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(2)} MB`}
function statusClass(s){s=+s||0;return s>=500?'err':s>=400?'warn':s>=300?'info':'ok'}
function rows(items){return (items||[]).map(([k,v,c])=>`<div class="row"><b>${esc(k)}</b><span class="${c||''}">${esc(v)}</span></div>`).join('')||'<p class="sub">Aguardando dados.</p>'}
function bar(v){const w=Math.max(0,Math.min(100,Number(v)||0));return`<div class="bar"><i style="width:${w}%"></i></div>`}
function apiBase(){const p=new URLSearchParams(location.search);return (p.get('apiBase')||localStorage.getItem('valorae:apiBase')||'').replace(/\/$/,'')}
function apiUrl(path){return (apiBase()||'')+path}
function headers(path){const internal=/\/api\/(server\/metrics|ready|cache\/stats|source\/status|openapi|fields|errors|v1\/release\/readiness)/.test(path);return {'accept':'application/json','x-valorae-app':'VALORAE Proxy Monitor','x-valorae-channel':internal?'dashboard-internal':'monitor-user-action','x-valorae-telemetry':internal?'dashboard':'proxy-output-probe'}}
async function api(path,opt={}){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),opt.timeout||9000);try{const r=await fetch(apiUrl(path),{cache:'no-store',signal:ctrl.signal,headers:{...headers(path),...(opt.headers||{})}});const txt=await r.text();let json={};try{json=txt?JSON.parse(txt):{}}catch{json={raw:txt}} if(!r.ok)throw Object.assign(new Error(json.error||`HTTP ${r.status}`),{status:r.status,json});return json}finally{clearTimeout(t)}}
function go(page){page=pageAliases[page]||page||'command';q('.nav button').forEach(b=>b.classList.toggle('active',(pageAliases[b.dataset.page]||b.dataset.page)===page));q('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.body.classList.remove('menuOpen');history.replaceState(null,'','#'+page);localStorage.setItem('valorae:monitorPage',page)}
q('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('menuBtn').onclick=()=>document.body.classList.toggle('menuOpen');$('overlay').onclick=()=>document.body.classList.remove('menuOpen');
function notice(msg,type='info'){const n=$('notice');n.className='notice show '+type;n.textContent=msg;clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),4500)}function clearNotice(){$('notice').classList.remove('show')}
function getEvents(m){const pom=m.proxyOutputMonitor||{};return (pom.outputFeed||m.recentEvents||[]).slice().sort((a,b)=>new Date(b.at||b.time||0)-new Date(a.at||a.time||0))}
function derive(m){const s=m.summary||{},pom=m.proxyOutputMonitor||{},dh=m.deliveryHarmony||{},pr=m.personalReleaseReadiness||{},events=getEvents(m),last=events[0]||{},sig=last.payloadSignals||{};return {s,pom,dh,pr,events,last,sig,vr:m.vercelRuntime||{},routes:pom.routeOutputs||m.routeDetails||[],dist:m.distributions||{}}}
function kpi(label,value,sub,cls=''){return`<div class="card metric"><div class="k">${esc(label)}</div><div class="v ${cls}">${esc(value)}</div><div class="sub">${esc(sub||'')}</div></div>`}
function renderKpis(d){const payloads=d.pom?.totals?.payloadResponses??d.dh?.payloadsDelivered??0;const renderRate=d.dh?.renderSafeRatePercent??d.s?.renderSafeRatePercent;const cacheRate=d.dh?.cacheSafeRatePercent??d.s?.cacheSafeRatePercent;const score=d.pr?.score??d.dh?.captureScore??'—';$('kpiGrid').innerHTML=[kpi('Requisições',fmt(d.s.requests??d.s.totalRequests??0),'Chamadas úteis capturadas'),kpi('Payloads entregues',fmt(payloads),'Saídas para apps/usuários','ok'),kpi('Render safe',renderRate!=null?`${Math.round(renderRate)}%`:'—','Segurança de tela'),kpi('Readiness',score==='—'?'—':`${score}/100`,d.pr?.status||'maturidade pessoal')].join('')}
function insight(title,detail,cls=''){return`<div class="insight ${cls}"><b>${esc(title)}</b><br><small>${esc(detail)}</small></div>`}
function renderCommand(d){const apps=new Map();for(const e of d.events){const name=e.appName||e.app||'app não identificado',ch=e.appChannel||e.channel||'canal padrão';const k=name+' · '+ch;apps.set(k,(apps.get(k)||0)+1)}$('appsSummary').innerHTML=Array.from(apps.entries()).slice(0,7).map(([k,v])=>insight(k,`${v} respostas capturadas`)).join('')||insight('Sem tráfego externo ainda','Gere uma saída teste ou abra o app consumidor apontando para este deploy.','warn');const alerts=[];if((d.events||[]).length===0)alerts.push(['Feed vazio','Nenhuma resposta de app/usuário foi capturada nesta instância.','warn']);if(d.pr?.status&&d.pr.status!=='controlled-ready')alerts.push(['Readiness exige atenção',d.pr.status,'warn']);if(d.sig?.payloadBudgetState&&String(d.sig.payloadBudgetState).includes('heavy'))alerts.push(['Payload pesado','Use view=app ou compact para mobile.','warn']);if(d.sig?.fieldConsistencyIssues>0)alerts.push(['Campos suspeitos',`${d.sig.fieldConsistencyIssues} possíveis inconsistências financeiras.`,'warn']);if(!alerts.length)alerts.push(['Operação estável','Sem alertas críticos no snapshot atual.','ok']);$('executiveAlerts').innerHTML=alerts.map(a=>insight(...a)).join('');$('pipelineFacts').innerHTML=rows([['Runtime',d.vr.environment||d.vr.env||'local/indefinido'],['Host observado',d.vr.observed?.lastHost||d.vr.host||'—'],['Região',d.vr.observed?.lastRegion||d.vr.region||'—'],['Patch UI','21.12.31 redesign + 21.12.32 performance']])}
function eventCard(e,i){const roots=e.payloadRoots||e.roots||[];return`<div class="event ${state.selected===e?'sel':''}" data-i="${i}"><div class="meta"><b>${esc(e.route||e.path||'rota')}</b><span class="badge ${statusClass(e.status||e.statusCode)}">${esc(e.status||e.statusCode||'—')}</span></div><small>${esc(e.appName||e.app||'app')} · ${esc(e.appChannel||e.channel||'canal')} · ${fmtBytes(e.bytesOut||e.bytes||0)} · ${fmtMs(e.latencyMs)}</small><br><small>${esc((roots||[]).slice(0,5).join(', ')||e.payloadKind||'payload')}</small></div>`}
function applyFilters(){const qv=($('feedSearch')?.value||'').toLowerCase(),st=$('feedStatus')?.value||'',root=$('feedPayload')?.value||'',sort=$('feedSort')?.value||'recent';let arr=state.feed.filter(e=>{const text=[e.route,e.path,e.ticker,e.appName,e.app,e.appChannel,e.channel].join(' ').toLowerCase();const roots=e.payloadRoots||[];return (!qv||text.includes(qv))&&(!st||String(e.status||e.statusCode)===st)&&(!root||roots.includes(root)||JSON.stringify(e.payloadSignals||{}).includes(root))});if(sort==='bytes')arr.sort((a,b)=>(b.bytesOut||0)-(a.bytesOut||0));else if(sort==='latency')arr.sort((a,b)=>(b.latencyMs||0)-(a.latencyMs||0));state.filtered=arr;$('feedList').innerHTML=arr.map(eventCard).join('')||'<p class="sub">Nenhuma saída do proxy corresponde aos filtros.</p>';q('#feedList .event').forEach(el=>el.onclick=()=>selectEvent(arr[+el.dataset.i]));if(!state.selected&&arr[0])selectEvent(arr[0],true)}
function selectEvent(e,silent=false){state.selected=e;q('#feedList .event').forEach((el,i)=>el.classList.toggle('sel',state.filtered[i]===e));const sig=e?.payloadSignals||{},roots=e?.payloadRoots||[];$('selectedEvent').innerHTML=e?rows([['Rota',e.route||e.path],['App',e.appName||e.app||'—'],['Canal',e.appChannel||e.channel||'—'],['Status',e.status||e.statusCode||'—',statusClass(e.status||e.statusCode)],['Latência',fmtMs(e.latencyMs)],['Bytes',fmtBytes(e.bytesOut||e.bytes||0)],['Ticker/view',[e.ticker,e.view].filter(Boolean).join(' · ')||'—'],['Raízes',roots.join(', ')||'—'],['Métricas',sig.metrics??'—'],['Gráficos',`${sig.charts??0} séries · ${sig.chartPoints??0} pontos`],['Dividendos',sig.dividends??'—']]):'<p class="sub">Selecione uma resposta.</p>';$('payloadPreview').textContent=e?JSON.stringify(e.payloadPreview||e.preview||e.payloadSignals||e,null,2):'Selecione uma saída do proxy.';if(!silent)notice('Resposta selecionada no feed.','ok')}
['feedSearch','feedStatus','feedPayload','feedSort'].forEach(id=>{setTimeout(()=>$(id)&&($(id).oninput=applyFilters,$(id).onchange=applyFilters),0)});
function routeRows(routes){const arr=Array.isArray(routes)?routes:Object.entries(routes||{}).map(([route,v])=>({route,...v}));return arr.slice(0,20).map(r=>`<tr><td>${esc(r.route||r.path||'—')}</td><td>${fmt(r.responses||r.count||r.total||0)}</td><td>${esc(r.topApp||r.appName||'—')}</td><td>${r.renderSafeRatePercent!=null?Math.round(r.renderSafeRatePercent)+'%':'—'}</td><td>${fmtBytes(r.avgBytesOut||r.bytesOut||r.totalBytesOut||0)}</td></tr>`).join('')||'<tr><td colspan="5">Aguardando tráfego de saída.</td></tr>'}
function renderPerformance(d){$('vercelBox').innerHTML=rows([['Ambiente',d.vr.environment||d.vr.env||'local'],['URL/deploy',d.vr.url||d.vr.deployUrl||'—'],['Host observado',d.vr.observed?.lastHost||d.vr.host||'—'],['Região',d.vr.observed?.lastRegion||d.vr.region||'—'],['País/edge',d.vr.observed?.lastCountry||d.vr.country||'—'],['x-vercel-id',d.vr.observed?.lastVercelId||'—']]);$('routesTable').innerHTML=routeRows(d.routes)}
function renderQuality(d){const score=d.sig.fieldConsistencyScore??d.dh.avgFieldConsistencyScore??'—';const budget=d.sig.payloadBudgetBytes||d.last.bytesOut||0;const action=d.sig.assetActionDecision||'aguardando';$('qualityKpis').innerHTML=[kpi('Consistência',score==='—'?'—':`${score}/100`,d.sig.fieldConsistencyState||'campos financeiros'),kpi('Payload',fmtBytes(budget),d.sig.payloadBudgetState||'orçamento mobile'),kpi('Plano de ação',action,d.sig.assetActionScore?`${d.sig.assetActionScore}/100`:'decisão do engine'),kpi('Maturidade',d.pr.score?`${d.pr.score}/100`:'—',d.pr.status||'release pessoal'),kpi('Runtime',d.sig.engineRuntimeScore?`${d.sig.engineRuntimeScore}/100`:'—',d.sig.engineRuntimeGrade||'profiler')].join('');$('fieldGuardBox').innerHTML=rows([['Score',score==='—'?'—':`${score}/100`],['Estado',d.sig.fieldConsistencyState||'aguardando'],['Issues',d.sig.fieldConsistencyIssues??'—'],['Render safe',d.sig.renderSafe??d.dh.renderSafeRatePercent??'—'],['Cache safe',d.sig.cacheSafe??d.dh.cacheSafeRatePercent??'—']]);$('payloadBudgetBox').innerHTML=rows([['Bytes último payload',fmtBytes(budget)],['Estado',d.sig.payloadBudgetState||'—'],['Raízes',d.last.payloadRoots?d.last.payloadRoots.length:'—'],['Recomendação','view=app para produção, full só para auditoria']]);$('actionPlanBox').innerHTML=rows([['Ticker',d.last.ticker||d.sig.ticker||'—'],['Decisão',action],['Score',d.sig.assetActionScore?`${d.sig.assetActionScore}/100`:'—'],['Endpoint','/api/v1/asset/action-plan?ticker=PETR4'],['Performance','/api/v1/engine/performance?ticker=PETR4&view=app'],['Launch gate',d.sig.engineLaunchGateDecision||'—']]);$('maturityBox').innerHTML=rows([['Status',d.pr.status||'—'],['Score',d.pr.score?`${d.pr.score}/100`:'—'],['Público',d.pr.audience||'uso pessoal/pessoas próximas'],['Checklist',`${(d.pr.launchChecklist||[]).filter(x=>x.ok).length}/${(d.pr.launchChecklist||[]).length}`]]);const cov=d.sig.assetIndicatorCoverage||d.last.assetIndicatorCoverage||{};$('indicatorCoverageBox').innerHTML=rows([['Classe',d.last.assetType||d.last.type||'Ação/FII detectado pelo payload'],['Cobertura média',d.dh.avgIndicatorCoveragePercent?`${Math.round(d.dh.avgIndicatorCoveragePercent)}%`:'—'],['Campos detectados',d.sig.indicatorFields??d.sig.metrics??'—'],['Campos ausentes',Array.isArray(cov.missingCriticalFields)?cov.missingCriticalFields.slice(0,5).join(', '):'—']]);$('cacheSourceBox').innerHTML=rows([['Cache',d.last.cacheStatus||d.sig.cacheStatus||d.s.cacheStatus||'—'],['Fonte primária',d.last.primarySource||d.sig.primarySource||'—'],['Sources usadas',(d.last.sourcesUsed||[]).join(', ')||'—'],['Partial',d.last.partial??d.sig.partial??'—']])}
function renderIntegration(){const roots=[['Primeira pintura','appMobileSnapshot'],['Detalhe','appPayload'],['Cache','appSyncEnvelope'],['Segurança','appResponseIntegrity'],['Qualidade','fieldConsistencyGuard'],['Peso','payloadBudget'],['Decisão','assetActionPlan']];$('manifestBox').innerHTML=rows(roots.concat([['Headers','x-valorae-app, x-valorae-channel'],['View padrão','view=app'],['Profiler','engineRuntimeProfiler'],['Gate final','engineLaunchGate']]));$('promptGrid').innerHTML=prompts.map(p=>`<div class="stage prompt"><button class="btn copy" data-copy="${esc(p)}">copiar</button><small>${esc(p)}</small></div>`).join('');$('featuresGrid').innerHTML=features.map(f=>`<span class="badge ok">${esc(f)}</span>`).join('');$('techGrid').innerHTML=tech.map(([a,b])=>insight(a,b)).join('');$('moduleTree').innerHTML=moduleGroups.map(([k,t,d])=>`<div class="module-node"><b>${esc(t)}</b><br><small class="mono">${esc(d)}</small></div>`).join('');q('.copy').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(b.dataset.copy||'');notice('Prompt copiado.','ok')})}
function renderDiagnostics(m){$('rawMetrics').textContent=JSON.stringify({summary:m.summary,proxyOutputMonitor:m.proxyOutputMonitor,deliveryHarmony:m.deliveryHarmony,vercelRuntime:m.vercelRuntime,personalReleaseReadiness:m.personalReleaseReadiness,distributions:m.distributions},null,2)}
function seriesFromEvents(events,key){return events.slice(0,40).reverse().map((e,i)=>({x:i,y:Number(key(e))||0}))}
function drawLine(canvasId,pts,opts={}){const c=$(canvasId);if(!c)return;const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(320,r.width*dpr);c.height=Math.max(180,r.height*dpr);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=r.width,h=r.height,p=26;if(!c._setup){c._setup=true;const getPos=e=>{const rect=c.getBoundingClientRect();const clientX=e.touches?e.touches[0].clientX:e.clientX;const clientY=e.touches?e.touches[0].clientY:e.clientY;return{x:clientX-rect.left,y:clientY-rect.top};};const onMove=e=>{if(e.cancelable&&e.touches)e.preventDefault();const pos=getPos(e);c._mx=pos.x;c._my=pos.y;c._hover=true;if(c._draw)c._draw()};const onLeave=()=>{c._hover=false;if(c._draw)c._draw()};c.addEventListener('mousemove',onMove);c.addEventListener('touchmove',onMove,{passive:false});c.addEventListener('touchstart',onMove,{passive:false});c.addEventListener('mouseleave',onLeave);c.addEventListener('touchend',onLeave);}c._draw=()=>{ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=p+(h-2*p)*i/3;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const max=Math.max(1,...pts.map(x=>x.y));ctx.strokeStyle=opts.color||'#22c77c';ctx.lineWidth=2.4;ctx.beginPath();pts.forEach((pt,i)=>{const x=p+(w-2*p)*(pts.length<=1?0:i/(pts.length-1)),y=h-p-(h-2*p)*(pt.y/max);pt._x=x;pt._y=y;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='rgba(34,199,124,.12)';ctx.lineTo(w-p,h-p);ctx.lineTo(p,h-p);ctx.closePath();ctx.fill();ctx.fillStyle='#a0aca5';ctx.font='12px system-ui';ctx.fillText(opts.label||'',p,16);if(c._hover){let closest=null,minDist=Infinity;pts.forEach(pt=>{const dx=pt._x-c._mx,dy=pt._y-c._my,dist=dx*dx+dy*dy;if(dist<minDist){minDist=dist;closest=pt}});if(closest&&minDist<8000){ctx.beginPath();ctx.moveTo(closest._x,p);ctx.lineTo(closest._x,h-p);ctx.strokeStyle='rgba(255,255,255,0.2)';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(closest._x,closest._y,6,0,2*Math.PI);ctx.fillStyle='#22c77c';ctx.shadowColor='rgba(34,199,124,0.6)';ctx.shadowBlur=10;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='600 13px system-ui';ctx.textAlign='center';ctx.fillText(closest.y,closest._x,closest._y-16);ctx.textAlign='left'}}};c._draw()}
function drawBars(canvasId,items){const c=$(canvasId);if(!c)return;const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(320,r.width*dpr);c.height=Math.max(180,r.height*dpr);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=r.width,h=r.height,p=26;if(!c._setup){c._setup=true;const getPos=e=>{const rect=c.getBoundingClientRect();const clientX=e.touches?e.touches[0].clientX:e.clientX;const clientY=e.touches?e.touches[0].clientY:e.clientY;return{x:clientX-rect.left,y:clientY-rect.top};};const onMove=e=>{if(e.cancelable&&e.touches)e.preventDefault();const pos=getPos(e);c._mx=pos.x;c._my=pos.y;c._hover=true;if(c._draw)c._draw()};const onLeave=()=>{c._hover=false;if(c._draw)c._draw()};c.addEventListener('mousemove',onMove);c.addEventListener('touchmove',onMove,{passive:false});c.addEventListener('touchstart',onMove,{passive:false});c.addEventListener('mouseleave',onLeave);c.addEventListener('touchend',onLeave);}c._draw=()=>{ctx.clearRect(0,0,w,h);const vals=items.map(x=>x[1]),max=Math.max(1,...vals),bw=(w-2*p)/Math.max(1,items.length);let hovIdx=-1;if(c._hover){items.forEach((_,i)=>{const bx=p+i*bw+4;if(c._mx>=bx&&c._mx<=bx+bw-8)hovIdx=i})}items.forEach(([label,val],i)=>{const x=p+i*bw+4,bh=(h-2*p)*(val/max);ctx.fillStyle=i===hovIdx?'#3be293':(i%2?'#0d8d5b':'#22c77c');if(i===hovIdx){ctx.shadowColor='rgba(34,199,124,0.5)';ctx.shadowBlur=12;}else{ctx.shadowBlur=0;}ctx.fillRect(x,h-p-bh,Math.max(8,bw-8),bh);ctx.shadowBlur=0;ctx.fillStyle=i===hovIdx?'#fff':'#a0aca5';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(String(label).slice(0,8),x+Math.max(8,bw-8)/2,h-8);if(i===hovIdx){ctx.fillStyle='#fff';ctx.font='600 13px system-ui';ctx.fillText(val,x+Math.max(8,bw-8)/2,h-p-bh-8)}});ctx.fillStyle='#a0aca5';ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText('Distribuição de status',p,16)};c._draw()}
function drawAll(d){drawLine('flowChart',seriesFromEvents(d.events,e=>1),{label:'respostas por evento'});drawLine('latencyChart',seriesFromEvents(d.events,e=>e.latencyMs),{label:'latência ms'});drawLine('bytesChart',seriesFromEvents(d.events,e=>e.bytesOut||e.bytes),{label:'bytes enviados'});const status={};for(const e of d.events){const s=String(e.status||e.statusCode||'—');status[s]=(status[s]||0)+1}drawBars('statusChart',Object.entries(status).slice(0,8))}
function render(m){state.metrics=m;const d=derive(m);state.feed=d.events;localStorage.setItem('valorae:lastGoodServerMetrics',JSON.stringify({at:Date.now(),m}));$('liveBadge').textContent='● online';$('liveBadge').className='pill ok';$('readinessBadge').textContent=d.pr?.status?`readiness ${d.pr.status}`:'readiness —';renderKpis(d);renderCommand(d);applyFilters();renderPerformance(d);renderQuality(d);renderIntegration();renderDiagnostics(m);drawAll(d)}
function renderFailure(e){$('liveBadge').textContent='● falha de conexão';$('liveBadge').className='pill err';notice('Não consegui ler /api/server/metrics: '+e.message+'. Exibindo último snapshot local, se existir.','err');try{const old=JSON.parse(localStorage.getItem('valorae:lastGoodServerMetrics')||'null');if(old?.m)render(old.m)}catch{}}
async function refresh(opt={}){if((state.paused||state.hidden)&&!opt.force)return;try{const data=await api('/api/server/metrics',{timeout:opt.timeout||7000});render(data);if(!opt.silent)clearNotice()}catch(e){renderFailure(e)}}
async function probe(){clearNotice();const t=String($('tickerInput').value||'PETR4').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12)||'PETR4',view=$('viewSelect').value||'app';$('testResults').innerHTML='<p class="sub">Gerando saída real em /api/asset...</p>';try{const p=await api(`/api/asset?ticker=${encodeURIComponent(t)}&view=${encodeURIComponent(view)}&includeNews=1&mode=super&app=VALORAE%20Proxy%20Monitor&channel=proxy-output-probe`,{timeout:14000,headers:{'x-valorae-app':'VALORAE Proxy Monitor','x-valorae-channel':'proxy-output-probe'}});localStorage.setItem('valorae:lastGoodAsset',JSON.stringify(p));$('testResults').innerHTML=rows([['Ticker',p.ticker||t],['Status',p.status||'OK'],['Raízes entregues',Object.keys(p||{}).slice(0,18).join(', ')],['Snapshot mobile',p.appMobileSnapshot?'sim':'não'],['App payload',p.appPayload?'sim':'não'],['Engine efficiency',p.engineEfficiency?'sim':'não']]);notice('Saída de teste gerada. Ela deve aparecer no feed como resposta enviada pelo proxy.','ok');await refresh({force:true})}catch(e){notice('Falha ao gerar saída de teste: '+e.message,'err');$('testResults').innerHTML=rows([['Erro',e.message],['Status',e.status||'—']]);await refresh({force:true,silent:true})}}
function benchTable(b){if(!b)return'';const bench=b.benchmark||{},rowsB=Object.values(bench).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.iterations}</td><td>${x.avgMs}ms</td><td>${x.p50Ms}ms</td><td>${x.p95Ms}ms</td></tr>`).join('');return `<div class="grid g3"><div class="card soft"><div class="k">Score</div><div class="v">${b.score}/100</div><div class="sub">${b.mode} · ${b.durationMs}ms</div></div><div class="card soft"><div class="k">Checks OK</div><div class="v">${(b.checks||[]).filter(x=>x.ok).length}/${(b.checks||[]).length}</div><div class="sub">runtime, selectors, cache e PWA</div></div><div class="card soft"><div class="k">Recomendações</div><div class="v">${(b.recommendations||[]).length}</div><div class="sub">ações sugeridas</div></div></div><div class="scroll section"><table><thead><tr><th>Caso</th><th>Iterações</th><th>Média</th><th>P50</th><th>P95</th></tr></thead><tbody>${rowsB}</tbody></table></div><h3>Checks</h3>${(b.checks||[]).map(c=>`<div class="stage ${c.ok?'ok':'warn'}"><b>${esc(c.label)}</b> <span class="badge ${c.ok?'ok':'warn'}">${c.ok?'OK':'atenção'}</span><br><small>${esc(c.value||'')}</small></div>`).join('')}<h3>Recomendações</h3>${(b.recommendations||[]).map(r=>`<div class="stage ${r.level==='ok'?'ok':r.level==='warn'?'warn':'info'}"><b>${esc(r.title)}</b><br><small>${esc(r.detail)}</small></div>`).join('')}`}
async function runBenchmark(mode='quick'){$('benchBadge').textContent='executando '+mode;$('benchmarkResults').innerHTML='<p class="sub">Executando laboratório...</p>';try{const b=await api(`/api/server/tests?mode=${mode}`,{timeout:mode==='deep'?30000:16000});state.lastBench=b;$('benchBadge').textContent=`score ${b.score}/100`;$('benchBadge').className='badge '+(b.score>=80?'ok':'warn');$('benchmarkResults').innerHTML=benchTable(b)}catch(e){$('benchBadge').textContent='falha';$('benchBadge').className='badge err';$('benchmarkResults').innerHTML=rows([['Erro',e.message],['Status',e.status||'—']])}}
async function runNetworkProbes(){if(!state.lastBench)await runBenchmark('quick');const plan=state.lastBench?.network?.probePlan||[];$('benchmarkResults').innerHTML+='<h3>Probes de rede</h3><div id="networkProbeList"></div>';const list=$('networkProbeList');for(const p of plan){const t0=performance.now();try{const r=await fetch(apiUrl(p.url),{headers:{...headers(p.url),'x-valorae-telemetry':'dashboard-test'},cache:'no-store'});list.innerHTML+=`<div class="stage ${r.status===p.expectedStatus?'ok':'warn'}"><b>${esc(p.label)}</b> · ${r.status}<br><small>${Math.round(performance.now()-t0)}ms · ${esc(p.url)}</small></div>`}catch(e){list.innerHTML+=`<div class="stage err"><b>${esc(p.label)}</b><br><small>${esc(e.message)}</small></div>`}}}
function exportJson(){const data=JSON.stringify(state.metrics||{},null,2);navigator.clipboard?.writeText(data);notice('JSON atual copiado para a área de transferência.','ok')}
function exportCsv(){const header=['at','route','status','app','channel','ticker','bytesOut','latencyMs','payloadKind'];const lines=[header.join(',')].concat((state.filtered||state.feed).map(e=>header.map(k=>'"'+String(e[k]??(k==='app'?e.appName:k==='channel'?e.appChannel:'' )).replace(/"/g,'""')+'"').join(',')));navigator.clipboard?.writeText(lines.join('\n'));notice('CSV do feed copiado para a área de transferência.','ok')}
function clearFilters(){['feedSearch','feedStatus','feedPayload'].forEach(id=>{if($(id))$(id).value=''});if($('feedSort'))$('feedSort').value='recent';applyFilters()}

$('menuToggleBtn').onclick = (e) => {
  e.stopPropagation();
  $('actionMenu').classList.toggle('show');
};
document.addEventListener('click', (e) => {
  if (!$('topActionsContainer').contains(e.target)) {
    $('actionMenu').classList.remove('show');
  }
});


$('apiBaseBtn').onclick=()=>{
  const cur = apiBase() || location.origin;
  $('apiBaseInput').value = cur;
  $('apiConfigModal').classList.remove('hidden');
  $('actionMenu').classList.remove('show');
};
$('apiConfigCancel').onclick=()=>{
  $('apiConfigModal').classList.add('hidden');
};
$('apiConfigSave').onclick=()=>{
  const v = $('apiBaseInput').value.trim();
  if(v) {
    localStorage.setItem('valorae:apiBase', String(v).replace(/\/$/, ''));
    refresh({force:true});
  }
  $('apiConfigModal').classList.add('hidden');
};
$('refreshBtn').onclick=()=>{
       $('actionMenu').classList.remove('show');
       $('refreshBtn').classList.add('active-state');
       setTimeout(()=>$('refreshBtn').classList.remove('active-state'), 400);
       refresh({force:true});
    };$('pauseBtn').onclick=()=>{
      state.paused=!state.paused;
      $('pauseBtn').textContent=state.paused?'Retomar':'Pausar';
      if(state.paused) {
        $('pauseBtn').classList.add('paused-state');
      } else {
        $('pauseBtn').classList.remove('paused-state');
      }
      refresh({force:true});
    };
$('probeBtn').onclick=probe;$('benchQuickBtn').onclick=()=>runBenchmark('quick');$('benchDeepBtn').onclick=()=>runBenchmark('deep');$('networkProbeBtn').onclick=runNetworkProbes;$('exportJsonBtn').onclick=exportJson;$('exportCsvBtn').onclick=exportCsv;$('clearFiltersBtn').onclick=clearFilters;
window.addEventListener('resize',()=>state.metrics&&drawAll(derive(state.metrics)));document.addEventListener('visibilitychange',()=>{state.hidden=document.hidden;if(!state.hidden)refresh({force:true,silent:true})});
const initial=(location.hash||'').replace('#','')||localStorage.getItem('valorae:monitorPage');go(initial||'command');refresh({silent:true});state.timer=setInterval(()=>refresh({silent:true}),3000);
})();
